/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0f5238",
        "primary-container": "#2d6a4f",
        "primary-fixed": "#b1f0ce",
        "on-primary": "#ffffff",
        "on-primary-container": "#a8e7c5",
        secondary: "#8e4e14",
        "secondary-container": "#ffab69",
        "secondary-fixed": "#ffdcc4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#783d01",
        tertiary: "#005236",
        "tertiary-container": "#006d48",
        "tertiary-fixed": "#92f7c3",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#fcf9f3",
        "surface-bright": "#fcf9f3",
        "surface-dim": "#dcdad4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ed",
        surface_container: "#f0eee8",
        "surface-container-high": "#ebe8e2",
        "surface-container-highest": "#e5e2dc",
        "surface-variant": "#e5e2dc",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#404943",
        outline: "#707973",
        "outline-variant": "#bfc9c1",
        "role-accent": "#E9C46A",
        "transit-blue": "#168AAD",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      boxShadow: {
        soft: "0 4px 20px -4px rgba(15,82,56,0.08)",
        card: "0 4px 20px rgba(15,82,56,0.06)",
      },
    },
  },
  plugins: [],
}

